import type { AppData } from "./types";
import { weekStartIso } from "./dates";

export function createSeed(): AppData {
  return {
    weeklyGoal: 3,
    intention: {
      weekStart: weekStartIso(),
      text: "One slow morning together — phones stay in the other room until the coffee is gone.",
    },
    partner: {
      name: "Maya Chen",
      nickname: "May",
      pronouns: "she/her",
      howWeMet: "A friend's gallery opening in RiNo, spring 2018. She was arguing with the bartender about oat milk. You took her side.",
      notes: "Gets quiet when she's overwhelmed — that's when a walk helps more than a talk. Hates being late, loves a handwritten anything.",
      loveLanguages: ["Quality Time", "Words of Affirmation"],
      likes: [
        "Oat lattes",
        "Trail running",
        "Ceramic mugs",
        "Sunday crossword",
        "Radiohead",
        "Thai food",
        "Handwritten notes",
        "Moss green",
      ],
      dislikes: ["Surprise parties", "Being late", "Overly sweet desserts", "Public spectacle"],
      shirtSize: "M",
      shoeSize: "8.5",
      ringSize: "6",
      favoriteColor: "Moss",
      favoriteFlower: "Ranunculus",
      favoriteFood: "Pad see ew",
      favoriteDrink: "Oat latte, extra shot",
      favoriteMovie: "Before Sunrise",
      favoriteSong: "Weird Fishes / Arpeggi",
    },
    dates: [
      {
        id: "d-mom",
        title: "Maya's mom's birthday",
        kind: "custom",
        month: 10,
        day: 5,
        year: 1968,
        recursYearly: true,
        notes: "Call in the morning. Ranunculus if you can find them — cream and blush, not red.",
        remindDays: [21, 14, 7, 1],
      },
      {
        id: "d-santafe",
        title: "Weekend in Santa Fe",
        kind: "custom",
        month: 10,
        day: 17,
        year: 2026,
        recursYearly: false,
        notes: "She mentioned the plaza bookshop. Leave Saturday morning, no itinerary after lunch.",
        remindDays: [14, 7, 2],
      },
      {
        id: "d-bday",
        title: "Maya's birthday",
        kind: "birthday",
        month: 11,
        day: 8,
        year: 1994,
        recursYearly: true,
        notes: "Quiet dinner, not a party. The moss linen robe is the gift. Write the card the night before.",
        remindDays: [21, 14, 7, 1],
      },
      {
        id: "d-first",
        title: "First date",
        kind: "first",
        month: 4,
        day: 3,
        year: 2018,
        recursYearly: true,
        notes: "Tacos on Colfax. Recreate it or just mention it — she remembers the song that was playing.",
        remindDays: [7, 1],
      },
      {
        id: "d-anniv",
        title: "Our anniversary",
        kind: "anniversary",
        month: 6,
        day: 14,
        year: 2019,
        recursYearly: true,
        notes: "The year you made it official. She still has the receipt from that diner in her journal.",
        remindDays: [30, 14, 7, 1],
      },
    ],
    ideas: [
      {
        id: "i-robe",
        kind: "gift",
        title: "Moss linen robe",
        notes: "Mid-weight, shawl collar. Not the cheap one — she notices fabric. Wrap with a note, not a bow.",
        tags: ["birthday", "home"],
        status: "planned",
        occasion: "Maya's birthday",
        createdAt: "2026-08-02",
      },
      {
        id: "i-pour",
        kind: "gift",
        title: "Hasami pour-over cone",
        notes: "She outgrew the plastic one. Pair with a bag from the shop on 32nd.",
        tags: ["coffee", "home"],
        status: "idea",
        occasion: "",
        createdAt: "2026-09-01",
      },
      {
        id: "i-vinyl",
        kind: "gift",
        title: "Clean copy of OK Computer",
        notes: "Only if you find one in good shape. Don't force it.",
        tags: ["music"],
        status: "idea",
        occasion: "",
        createdAt: "2026-07-18",
      },
      {
        id: "i-ceramics",
        kind: "date",
        title: "Ceramics workshop in RiNo",
        notes: "Saturday morning class. She already liked the studio from the window.",
        tags: ["hands", "city"],
        status: "planned",
        occasion: "",
        createdAt: "2026-09-04",
      },
      {
        id: "i-rocks",
        kind: "date",
        title: "Sunset picnic at Red Rocks",
        notes: "Thermos of tea, the good blanket, leave phones in the car. Go on a weeknight if the lot is empty.",
        tags: ["outdoors", "quiet"],
        status: "idea",
        occasion: "",
        createdAt: "2026-08-21",
      },
      {
        id: "i-thai",
        kind: "date",
        title: "Cook a new Thai recipe together",
        notes: "No recipe-scrolling at the table. Pick the dish in the morning. Pad see ew is already hers — try something she hasn't made.",
        tags: ["home", "food"],
        status: "idea",
        occasion: "",
        createdAt: "2026-09-10",
      },
      {
        id: "i-ranunculus",
        kind: "gift",
        title: "Ranunculus — cream and blush",
        notes: "For Maya's mom. Not red. Call in the morning too.",
        tags: ["family", "flowers"],
        status: "idea",
        occasion: "Maya's mom's birthday",
        createdAt: "2026-09-08",
      },
      {
        id: "i-golden",
        kind: "date",
        title: "Breakfast in Golden, then a trail",
        notes: "Diner first, then the easy loop. She'll want to be back before the afternoon heat.",
        tags: ["outdoors", "morning"],
        status: "idea",
        occasion: "",
        createdAt: "2026-06-12",
      },
    ],
    gestures: [
      {
        id: "g-latte",
        title: "Oat latte after her long run",
        notes: "Caught her on the way back. She didn't ask.",
        date: "2026-09-18",
        kind: "gift",
      },
      {
        id: "g-pad",
        title: "Cooked pad see ew on a weeknight",
        notes: "Her favorite, extra basil. We ate on the floor.",
        date: "2026-09-16",
        kind: "time",
      },
      {
        id: "g-note",
        title: "Note in the laptop sleeve",
        notes: "Three sentences. She found it at work.",
        date: "2026-09-12",
        kind: "note",
      },
      {
        id: "g-wait",
        title: "Stayed up so we could talk about her week",
        notes: "She had the hard conversation with her director. Just listened.",
        date: "2026-09-07",
        kind: "time",
      },
    ],
    quality: [
      {
        id: "q-dinner",
        date: "2026-09-16",
        minutes: 90,
        title: "Weeknight dinner, phones away",
        notes: "Pad see ew. She talked. You listened.",
      },
      {
        id: "q-walk",
        date: "2026-09-18",
        minutes: 40,
        title: "Morning walk after her run",
        notes: "Slow loop around the park. Coffee on a bench.",
      },
    ],
    rituals: [
      {
        id: "r-morning",
        title: "Morning check-in",
        cadenceDays: 1,
        lastDone: "2026-09-20",
        notes: "A real sentence, not a heart emoji.",
      },
      {
        id: "r-friday",
        title: "Plan Friday night",
        cadenceDays: 7,
        lastDone: "2026-09-11",
        notes: "Decide by Wednesday so it doesn't become the couch by default.",
      },
      {
        id: "r-note",
        title: "Leave a small note",
        cadenceDays: 5,
        lastDone: "2026-09-13",
        notes: "Somewhere she'll find it without being handed it.",
      },
      {
        id: "r-dinner",
        title: "Phone-free dinner",
        cadenceDays: 7,
        lastDone: "2026-09-16",
        notes: "Even if it's leftovers.",
      },
    ],
  };
}

export function createEmpty(): AppData {
  return {
    weeklyGoal: 3,
    intention: { weekStart: weekStartIso(), text: "" },
    partner: {
      name: "",
      nickname: "",
      pronouns: "",
      howWeMet: "",
      notes: "",
      loveLanguages: [],
      likes: [],
      dislikes: [],
      shirtSize: "",
      shoeSize: "",
      ringSize: "",
      favoriteColor: "",
      favoriteFlower: "",
      favoriteFood: "",
      favoriteDrink: "",
      favoriteMovie: "",
      favoriteSong: "",
    },
    dates: [],
    ideas: [],
    gestures: [],
    quality: [],
    rituals: [],
  };
}
