/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotRouteImport } from './routes/bot'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as UsRouteImport } from './routes/us'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const UsRoute = UsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/dates': typeof DatesRoute
  '/ideas': typeof IdeasRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/unlock': typeof UnlockRoute
  '/us': typeof UsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/dates': typeof DatesRoute
  '/ideas': typeof IdeasRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/unlock': typeof UnlockRoute
  '/us': typeof UsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bot': typeof BotRoute
  '/dates': typeof DatesRoute
  '/ideas': typeof IdeasRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/unlock': typeof UnlockRoute
  '/us': typeof UsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bot'
    | '/dates'
    | '/ideas'
    | '/play'
    | '/privacy'
    | '/support'
    | '/unlock'
    | '/us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bot'
    | '/dates'
    | '/ideas'
    | '/play'
    | '/privacy'
    | '/support'
    | '/unlock'
    | '/us'
  id:
    | '__root__'
    | '/'
    | '/bot'
    | '/dates'
    | '/ideas'
    | '/play'
    | '/privacy'
    | '/support'
    | '/unlock'
    | '/us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotRoute: typeof BotRoute
  DatesRoute: typeof DatesRoute
  IdeasRoute: typeof IdeasRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  UnlockRoute: typeof UnlockRoute
  UsRoute: typeof UsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us': {
      id: '/us'
      path: '/us'
      fullPath: '/us'
      preLoaderRoute: typeof UsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotRoute: BotRoute,
  DatesRoute: DatesRoute,
  IdeasRoute: IdeasRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  UnlockRoute: UnlockRoute,
  UsRoute: UsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
